import { Song } from './types';

// Extended mock songs data for lessons page
export const mockLessonsData: (Song & { 
  duration: string; 
  progress: number; 
  difficulty: string;
})[] = [
  {
    id: 'song-1',
    title: 'Despacito',
    artist: 'Luis Fonsi ft. Daddy Yankee',
    language: 'spanish',
    level: 'beginner',
    genre: 'pop',
    coverUrl: 'https://images.pexels.com/photos/1001850/pexels-photo-1001850.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-1',
    popularity: 95,
    duration: '4:42',
    progress: 75,
    difficulty: 'Easy vocabulary, clear pronunciation',
    lyrics: []
  },
  {
    id: 'song-2',
    title: 'La Vie En Rose',
    artist: 'Édith Piaf',
    language: 'french',
    level: 'intermediate',
    genre: 'classic',
    coverUrl: 'https://images.pexels.com/photos/164821/pexels-photo-164821.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-2',
    popularity: 85,
    duration: '3:28',
    progress: 50,
    difficulty: 'Poetic language, moderate pace',
    lyrics: []
  },
  {
    id: 'song-3',
    title: 'Bailando',
    artist: 'Enrique Iglesias',
    language: 'spanish',
    level: 'intermediate',
    genre: 'pop',
    coverUrl: 'https://images.pexels.com/photos/2113566/pexels-photo-2113566.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-3',
    popularity: 88,
    duration: '4:03',
    progress: 25,
    difficulty: 'Fast rhythm, colloquial expressions',
    lyrics: []
  },
  {
    id: 'song-4',
    title: 'Je Veux',
    artist: 'Zaz',
    language: 'french',
    level: 'advanced',
    genre: 'jazz',
    coverUrl: 'https://images.pexels.com/photos/4087996/pexels-photo-4087996.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-4',
    popularity: 78,
    duration: '3:31',
    progress: 0,
    difficulty: 'Complex metaphors, varied tempo',
    lyrics: []
  },
  {
    id: 'song-5',
    title: 'Con te partirò',
    artist: 'Andrea Bocelli',
    language: 'italian',
    level: 'intermediate',
    genre: 'classical',
    coverUrl: 'https://images.pexels.com/photos/1407322/pexels-photo-1407322.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-5',
    popularity: 92,
    duration: '4:15',
    progress: 100,
    difficulty: 'Operatic style, emotional expression',
    lyrics: []
  },
  {
    id: 'song-6',
    title: 'Volare',
    artist: 'Domenico Modugno',
    language: 'italian',
    level: 'beginner',
    genre: 'folk',
    coverUrl: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-6',
    popularity: 89,
    duration: '3:45',
    progress: 0,
    difficulty: 'Simple vocabulary, upbeat rhythm',
    lyrics: []
  },
  {
    id: 'song-7',
    title: 'Atemlos durch die Nacht',
    artist: 'Helene Fischer',
    language: 'german',
    level: 'intermediate',
    genre: 'pop',
    coverUrl: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-7',
    popularity: 82,
    duration: '3:52',
    progress: 30,
    difficulty: 'Modern German, clear diction',
    lyrics: []
  },
  {
    id: 'song-8',
    title: '99 Luftballons',
    artist: 'Nena',
    language: 'german',
    level: 'advanced',
    genre: 'rock',
    coverUrl: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-8',
    popularity: 91,
    duration: '3:53',
    progress: 0,
    difficulty: 'Political themes, 80s slang',
    lyrics: []
  },
  {
    id: 'song-9',
    title: 'Manu Chao',
    artist: 'Bongo Bong',
    language: 'spanish',
    level: 'advanced',
    genre: 'reggae',
    coverUrl: 'https://images.pexels.com/photos/1699161/pexels-photo-1699161.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-9',
    popularity: 76,
    duration: '3:12',
    progress: 60,
    difficulty: 'Mixed languages, street slang',
    lyrics: []
  },
  {
    id: 'song-10',
    title: 'Sous le ciel de Paris',
    artist: 'Yves Montand',
    language: 'french',
    level: 'beginner',
    genre: 'chanson',
    coverUrl: 'https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-10',
    popularity: 84,
    duration: '3:20',
    progress: 0,
    difficulty: 'Classic French, slow tempo',
    lyrics: []
  },
  {
    id: 'song-11',
    title: 'Azzurro',
    artist: 'Adriano Celentano',
    language: 'italian',
    level: 'intermediate',
    genre: 'pop',
    coverUrl: 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-11',
    popularity: 87,
    duration: '4:28',
    progress: 15,
    difficulty: 'Descriptive language, moderate pace',
    lyrics: []
  },
  {
    id: 'song-12',
    title: 'Du hast',
    artist: 'Rammstein',
    language: 'german',
    level: 'beginner',
    genre: 'metal',
    coverUrl: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-12',
    popularity: 93,
    duration: '3:54',
    progress: 0,
    difficulty: 'Simple phrases, repetitive structure',
    lyrics: []
  },
  {
    id: 'song-13',
    title: 'Macarena',
    artist: 'Los Del Rio',
    language: 'spanish',
    level: 'beginner',
    genre: 'dance',
    coverUrl: 'https://images.pexels.com/photos/1001850/pexels-photo-1001850.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-13',
    popularity: 90,
    duration: '4:12',
    progress: 85,
    difficulty: 'Repetitive lyrics, party vocabulary',
    lyrics: []
  },
  {
    id: 'song-14',
    title: 'Non, je ne regrette rien',
    artist: 'Édith Piaf',
    language: 'french',
    level: 'advanced',
    genre: 'chanson',
    coverUrl: 'https://images.pexels.com/photos/164821/pexels-photo-164821.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-14',
    popularity: 88,
    duration: '2:23',
    progress: 40,
    difficulty: 'Philosophical themes, dramatic delivery',
    lyrics: []
  },
  {
    id: 'song-15',
    title: 'Felicità',
    artist: 'Al Bano & Romina Power',
    language: 'italian',
    level: 'beginner',
    genre: 'pop',
    coverUrl: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=600',
    audioUrl: 'mock-audio-url-15',
    popularity: 86,
    duration: '4:05',
    progress: 0,
    difficulty: 'Joyful vocabulary, duet format',
    lyrics: []
  }
];

export const genreOptions = ['All', 'Pop', 'Rock', 'Classical', 'Jazz', 'Folk', 'Reggae', 'Chanson', 'Dance', 'Metal'];
export const languageOptions = [
  { value: 'all', label: 'All Languages', flag: '🌍' },
  { value: 'spanish', label: 'Spanish', flag: '🇪🇸' },
  { value: 'french', label: 'French', flag: '🇫🇷' },
  { value: 'italian', label: 'Italian', flag: '🇮🇹' },
  { value: 'german', label: 'German', flag: '🇩🇪' }
];
export const levelOptions = ['All', 'Beginner', 'Intermediate', 'Advanced'];
export const durationOptions = ['All', 'Short (< 3 min)', 'Medium (3-4 min)', 'Long (> 4 min)'];